sudo: false

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

install:
  - pip install pytest codecov
  - pip install .

script:
  - pytest -v
  - pytest --cov-report term-missing --cov whomst

after_success:
  - codecov
