#!/bin/bash
# -*- coding: utf-8 -*-
echo "==>  gathering system facts"
echo "OS: " `uname`
echo "HOSTNAME: " `hostname`
echo "USER: " `whoami`
echo "PWD: " `pwd`


echo "==>  copying program files"
sudo cp ./whomst/__init__.py /usr/local/bin/whomst
ls -la /usr/local/bin/whomst


echo "==>  test installation"
cd ./tests
x=`whomst . | grep foo`
# echo "x=$x"
[ "$x" == "foo" ] && echo "ok" || echo "invalid"
y=`whomst . | grep bar`
# echo "y=$y"
[ "$y" == "bar" ] && echo "ok" || echo "invalid"
z=`whomst . | grep new`
# echo "z=$z"
[ "$z" == "new" ] && echo "ok" || echo "invalid"
